[platformio]
default_envs = m5stack-cardputer-adv
extra_configs =
    targets/*/platformio.ini

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
board_build.flash_size = 8MB
build_unflags =
    -DARDUINO_USB_MODE=1
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
    -DMANTIS_MSC_BUFFER_SIZE=8192
lib_deps =
    https://github.com/m5stack/M5Cardputer.git
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
