[env:m5stack-cardputer-adv]
board_build.partitions = targets/m5stack-cardputer-adv/partitions.csv
build_flags =
    ${env.build_flags}
    -DMANTIS_TARGET_CARDPUTER_ADV=1
    -I targets/m5stack-cardputer-adv
