#ifndef MANTIS_TARGET_CONFIG_H
#define MANTIS_TARGET_CONFIG_H

#define MANTIS_TARGET_NAME "M5Stack Cardputer ADV"
#define MANTIS_SD_SCK 40
#define MANTIS_SD_MISO 39
#define MANTIS_SD_MOSI 14
#define MANTIS_SD_CS 12
#define MANTIS_SD_FREQUENCY_HZ 25000000

#endif
